#!/bin/sh

# Handle X11 forwarding authentication
if read proto cookie; then
    if [ -n "$DISPLAY" ]; then
        echo "add $DISPLAY $proto $cookie" | xauth -q -
    fi
fi

# Fix SSH auth socket location so agent forwarding works with tmux.
if test "$SSH_AUTH_SOCK" ; then
  ln -sf $SSH_AUTH_SOCK ~/.ssh/ssh_auth_sock
fi

