name: Create Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e., v1.0, v2.0.1

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Create Release
      id: create_release
    - uses: ncipollo/release-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Changes in this release
        draft: false
        prerelease: false
